### PR TITLE
Create yaml.nanorc

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by serialhex** [comment]
Cool!  It looks pretty good, but I do have a Q:  the regex for booleans includes this section right here: `[Yy][Ee]?[Ss]?` which highlights `Y` and `yes`, their case-changed counterparts, along with the strange `ys`.  My mind isn't very regex-y at the moment and can't figure out a quick way to fix it.

If you can figure something out add it to your pull req and I'll pull it all in.  Otherwise, let me know and I'll leave it as-is.

Thanks for the PR!!

**Comment by Piterden** [comment]
I had hurried up a bit with it, you are absolutely right. Will be fixed soon...

**Comment by Piterden** [comment]
`true | True | TRUE | false | False | FALSE	 tag:yaml.org,2002:bool`

**Comment by serialhex** [comment]
Thank you!  I edited it a bit so it has a case-insensitive regex and less duplication.  The most recent nanorc docs are here: https://www.nano-editor.org/dist/v2.8/nanorc.5.html and apparently they've added a few new features I didn't know about... like you can suggest an external linter!!! o_O that's pretty cool!! :smile:

**Comment by Piterden** [comment]
I have an idea about `header`

**Pull request merged**
